### PR TITLE
Update PHP min & markdown version

### PR DESCRIPTION
**Pull request by maschmann**
* fixed interface missing return type
* PHP min version >= 7.3
* league/commonmark version ^1.0 

It's still not on current (2.0.2) because:
* the dependency commonmark has for league/config 1.1 resolves to 1.1.1 when installing within the bundle
* the lockfile commit puts the dependency to a hard 1.1.1 which make ist incompatible with sculpin's dep on 1.1.0

Since having the lockfile committed isn't the worst idea, so I kept it that way - makes stuff more reproducible.

### CODE REVIEW

**Comment by bcremer** [comment]
Thanks @maschmann for this PR.

I'm currently not using sculpin anymore for any projects I'm involved with so I'm unable to test this.

The biggest active consumer might be https://github.com/shopware/devdocs. @mitelg or @philipgatzka  maybe you can cross check if it works fine for you before I tag the release.

**Comment by maschmann** [comment]
No worries, was just fiddling with sculpin again, yesterday and needed the markdown implementation changed. Was too lazy to build it myself ;-)

**Comment by mitelg** [comment]
we are still using PHP 7.2 for the dev docs :see_no_evil: 

so right now, I cannot check, if this would work for us, as it probably needs some more adjustments, if we upgrade to  PHP >= 7.3

**Comment by maschmann** [comment]
@mitelg you can try it with 7.2 maybe. 7.0 did not work due to 7.1 as min dep for the league dependency :-D 
Most likely a 7.4 min version would be better ... 
Starting to get grey hair >.<

**Comment by bcremer** [comment]
@mitelg I added you as maintainer. Please adjust min versions as needed.

**Comment by mitelg** [comment]
@bcremer I tested the generation of our docs under PHP 7.4 with dev-master of this repo. It looks good so far. so from my side, we can tag it as new release :slightly_smiling_face: :+1:

**Comment by mitelg** [comment]
@maschmann @bcremer 0.5.0 release is out :tada:

**Comment by bcremer** [comment]
Thank you folks!

**Pull request merged**
